def dialogo_final():
    import time
    print('Você conseguiu!\n\nApós ser oferecida uma bolada de USD2.000.000,00 pela CIA para descobrir o que era o Elixir que tanto buscavam, e cujo valor ninguém conseguia realmente mensurar, a Professora Rafaela tomou uma medida drástica. Chamou seu esposo, prometendo a ele que se ganhassem o dinheiro da CIA, ela poderia comprar um PS5 pra ele. Ele topou o sequestro na hora.')
    time.sleep(10)
    print("Rafaela sequestrou em conjunto com a CIA a filha de Marco Paludo, que morava na Alemanha, a trouxe ao Brasil, e a fez de refem no Havana.")
    time.sleep(5)
    print('Bar fechado. Apenas Rafaela e seu esposo, e a filha de Paludo amarrada em uma cadeira. Os dois já estavam com tudo pronto para fugir do país, e apenas aguardavam Paludo. Limpavam cada um, sua respectiva arma... até que...')
    time.sleep(5)
    print('BAAAAAAM!!!!!!')
    time.sleep(2)
    print('Quando Paludo descobriu que sua prole estava em perigo, saiu imediatamente do seu jogo de Bocha e arrombou a porta do Havana com uma força sem igual. Ele usava um chapéu estranhamente volumoso.')
    time.sleep(1)
    print('DECÂNO: Você passou dos limites Kelly.')
    print('RAFAELA: Não precisamos machucar ninguém hoje. Você me conta o que é o Elixir, e vai ficar tudo bem. Nunca mais vai me ver de novo.')
    time.sleep(3)
    print('DECÂNO: Eu conto. Mas primeiro soltem minha filha, e guardem as armas.')
    time.sleep(5)
    print('RAFAELA: Ok.')
    print('As armas foram guardadas, a filha de Paludo estava finalmente a salvo. Hora dele honrar sua promessa.')
    time.sleep(5)
    print('DECÂNO: Eu sei que a CIA lhe ofereceu dinheiro. Mas já lhe aviso. Não vai receber nada.')
    print('ESPOSO: Você sabe quanto custa um PS5????? Estamos tod...')
    print('RAFAELA: Amor, agora não! Foco por favor!')
    time.sleep(5)
    print('RAFAELA: Como assim não vou receber nada?')
    time.sleep(3)
    print('DECÂNO: Simples. Quando falei que estava trabalhando em uma ciência extremamente complexa, que ainda não havia sido domada, todos pensaram que estava planejando a nova bomba atômica. CIA e KGB instalaram suas estações de trabalho, respectivamente no prédio Administrativo e no DCE.')
    print('DECÂNO: O que ninguém sabia, era que o meu projeto não tem absolutamente nada haver com a guerra fria.')
    time.sleep(3)
    print('DECÂNO: Há anos eu venho pesquisando uma cura... Há anos eu venho testando em coelhos, em cachorrinhos e até mesmo em mim... e finalmente eu consegui desenvolver o que queria...')
    for i in range(0,5):
        print('.\n')
        time.sleep(1)
    print('DECÂNO: A cura da calvice.')
    time.sleep(5)
    print('Com apenas um movimento, Paludo tira o chapéu, e mostra um moicano verde poderoso que o fazia parecer um punk dos anos 80.')
    time.sleep(3)
    print('A professora Rafaela olha incrédula. Seu esposo saca um celular para tirar uma foto, enquanto a filha de Paludo olha ao redor pra ver se não há nenhum conhecido em volta.')
    time.sleep(3)
    print('RAFAELA: Você tá brincando comigo né.')
    time.sleep(5)
    print('DECÂNO: Não (responde ajeitando o topo do moicano)')
    print('RAFAELA: Então quer dizer que todo esse trabalho, todo esse aue, toda esse mistério, mortes e etc, era por causa da p#rra da cura da calvice?')
    time.sleep(3)
    print('DECÂNO: Sim (Paludo testa uma franja nova enquanto fala)')
    print('RAFAELA: Isso não é mais sobre a cura da calvice, nem sobre a CIA ou até mesmo a KGB.')
    time.sleep(3)
    print('RAFAELA: ISSO É POR TER ME CHAMADO DE KELLY!')
    time.sleep(1)
    print("A professora Rafaela parte pra cima do Paludo e senta a porrada nele. Rafaela bateu tanto nele, que nem Deus o reconheceu quando chegou no céu.")
    time.sleep(8)
    print('Rafaela e seu esposo tinham tudo preparado para mudarem suas identidades e ir morar na Suíça. Quanto remorço ela carregaria no seu coração. Ainda com lágrimas no rosto, eles são expostos.\n\n')
    time.sleep(3)
    print('Como não conseguiram o dinheiro da CIA, resolveram se mudar para Sergipe, pois ninguém nunca vai pra lá, ou seja, nunca seriam descobertos e onde eles finalmente poderiam esquecer tudo o que aconteceu... Sendo algemados, ambos confessam o crime.\n')