def dialogo_final():
    import time
    print('Você conseguiu!\nAo saber que ')
    time.sleep(10)
    print("O novo brinquedo da CIA era um playstation 5.")
    time.sleep(5)
    print('DECÂNA: Curioso você me chamar aqui... Geralmente é a Sheila quem marca esses encontros, e nunca fazemos na sala da CIA. E o que seu esposo faz aqui?')
    time.sleep(5)
    print('ESPOSO: Você sabe quanto custa um PS5????? Estamos tod...')
    print('RAFAELA: Amor, agora não! Foco por favor!')
    time.sleep(3)
    print('RAFAELA: O motivo desta reunião é para saber onde você está com a cabeça. A CIA foi prometida a gerência do projeto há anos! O que aconteceu?')
    time.sleep(4)
    print('DECÂNA: O poder subiu a cabeça da CIA. Acha que não tive acesso aos planos de destruição de Moscou? Não posso deixar isso acontecer. E não venha com esse tom ameaçador pra cima de mim, Kelly. Todos sabemos que esse projeto precisa de pessoas neutras.')
    time.sleep(5)
    print('RAFAELA: Você não me deixa escolha.')
    time.sleep(3)
    print('A professora Rafaela pula de sua mesa, derruba a decâna ainda em sua cadeira, e no chão, pede que o esposo a alcance o machado.')
    time.sleep(3)
    print('DECÂNA: Você não precisa fazer isso... Não vai alterar a minha decisão!')
    time.sleep(5)
    print('RAFAELA: Isso não é mais sobre a bomba de hidrogênio, nem sobre a CIA ou até mesmo a KGB.')
    time.sleep(3)
    print('RAFAELA: ISSO É POR TER ME CHAMADO DE KELLY!')
    time.sleep(1)
    print("Com um golpe certeiro, a cabeça da decâna sai rolando, e o sangue começa a inundar a sala.")
    time.sleep(8)
    print('Rafaela e seu esposo tinham tudo preparado para mudarem suas identidades e ir morar na Suíça. Quanto remorço ela carregaria no seu coração. Ainda com lágrimas no rosto, eles são expostos.\n\n')
    print('Com as malas prontas para fugir do país para comprar um PS5 para seu esposo no Paraguai e depois fugir para o Havaí, onde eles finalmente poderiam esquecer tudo o que aconteceu... Sendo algemados, ambos confessam o crime.\n')